const getters = {
  //user
  token: state => state.user.token,
  userId: state => state.user.userId,
  userInfo: state => state.user.userInfo,
  userOrderList: state => state.user.userOrderList,
  hotelListLoading: state => state.hotel.hotelListLoading,
  hotelList: state => state.hotel.hotelList,
  hotelComments: state => state.hotel.hotelComments,
  currentHotelInfo: state => state.hotel.currentHotelInfo,
  currentHotelId: state => state.hotel.currentHotelId,
  orderModalVisible: state => state.hotel.orderModalVisible,
  currentOrderRoom: state => state.hotel.currentOrderRoom,
  orderMatchCouponList: state => state.hotel.orderMatchCouponList,
  hotelOrders: state => state.hotel.hotelOrders,
  rateOrderId: state => state.user.rateOrderId,
  currentOrderId: state => state.user.currentOrderId,
  rateHotelVisibleOfUser: state => state.user.rateHotelVisibleOfUser,
  orderDetailVisibleOfUser: state => state.user.orderDetailVisibleOfUser,
  currentOrderInfo: state => state.user.currentOrderInfo,
  //admin
  managerList: state => state.admin.managerList,
  addManagerModalVisible: state => state.admin.addManagerModalVisible,
  addManagerParams: state => state.admin.addManagerParams,
  userList: state => state.admin.userList,
  addUserModalVisible: state => state.admin.addUserModalVisible,
  addUserParams : state => state.admin.addUserParams,
  marketerList: state => state.admin.marketerList,
  addMarketerModalVisible: state => state.admin.addMarketerModalVisible,
  addMarketerParams:state => state.admin.addMarketerParams,
  //hotelManager
  orderList: state => state.hotelManager.orderList,
  activeManagerId: state => state.hotelManager.activeManagerId,
  addHotelModalVisible: state => state.hotelManager.addHotelModalVisible,
  addRoomModalVisible: state => state.hotelManager.addRoomModalVisible,
  couponVisible: state => state.hotelManager.couponVisible,
  addCouponVisible: state => state.hotelManager.addCouponVisible,
  activeHotelId: state => state.hotelManager.activeHotelId,
  couponList: state => state.hotelManager.couponList,
  //marketer
  marketerHotelId: state => state.marketer.marketerHotelId,
  marketerCouponList: state => state.marketer.marketerCouponList,
  addWebStrategyModalVisible:state => state.marketer.addWebStrategyModalVisible,
}
  
  export default getters